### ISSUE TITLE
Using the JpaTransactionManager

### ISSUE THREAD

**Issue by benas** [balu123456/offersEngine_Job#1]
Hi,

I open this issue to show you how to configure your project to use the `JpaTransactionManager` with Spring Batch according to: https://stackoverflow.com/questions/52178696/spring-boot-batch-with-jpapagingitemreader.

I see a couple of issues here:

* As mentioned in SO, you need to use version `4.1.0.M3` in order for the fix to work
* You need to remove the [`MapJobRespositoryFactoryBean`](https://github.com/balu123456/offersEngine_Job/blob/master/src/main/java/com/clearlane/offersengine_job/batchconfiguration/BatchScheduler.java#L52-L57) as this will create a map based job repository which does not use your transaction manager (but uses a `ResourcelessTransactionManager` instead)

Other than that, I don't see anything wrong with your config.

Let me know if you still have the issue.

Kr,
Mahmoud

**Comment by balu123456** [comment]
Sure, Thansk @benas for you support

**Comment by balu123456** [comment]
@benas : still the same issue i am getting. i am trying to different approach now using RepositoryItemReader. by giving methods its working awesome but i try to give native quires i am facing the issue. the issue "is it works,but return Object[]" below is my repository method 

@Query(value = "SELECT * FROM QUOTE_OFFER_FULFILLMENT QOF WHERE QOF.STATUS=?1 OR QOF.STATUS=?2  \n#pageable\n", nativeQuery = true)
    Page<QuoteOfferFulfillment> findTempByStatus(QuoteOfferFulfillmentStatus status,
            QuoteOfferFulfillmentStatus status1, Pageable pageable);

@Bean
    public RepositoryItemReader<QuoteOfferFulfillment> reader() {
        RepositoryItemReader<QuoteOfferFulfillment> fullfillment = new RepositoryItemReader<QuoteOfferFulfillment>();
        fullfillment.setRepository(fulfillmentRepository);
        fullfillment.setMethodName("findTempByStatus");
        List<QuoteOfferFulfillmentStatus> list = new ArrayList<QuoteOfferFulfillmentStatus>();
        list.add(QuoteOfferFulfillmentStatus.FULFILLMENT_READY);
        list.add(QuoteOfferFulfillmentStatus.FAILED);
        fullfillment.setPageSize(40);
        fullfillment.setArguments(list);
        HashMap<String, Direction> sorts = new HashMap<>();
        sorts.put("id", Direction.DESC);
        fullfillment.setSort(sorts);
        return fullfillment;
    }

did i done any thing wrong on this. Please let me know your comments / suggestions

**Comment by balu123456** [comment]
@benas : one small question, i try to upgrade spring batch to 4.1.0.m3 but some ohh maven dependencies are not available. it the maven it is available only 

<dependency>
    <groupId>org.springframework.batch</groupId>
    <artifactId>spring-batch-infrastructure</artifactId>
    <version>4.0.1.RELEASE</version>
</dependency>

If i am making any mistake please suggest me.

**Comment by balu123456** [comment]
@benas : i have written CustomJpaPagingItemReader just for work around.  below is my customJPAPagingItemReader class:

[package com.clearlane.offersengine_job.utils;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;

import org.springframework.batch.item.database.AbstractPagingItemReader;
import org.springframework.batch.item.database.orm.JpaQueryProvider;
import org.springframework.dao.DataAccessResourceFailureException;
import org.springframework.util.Assert;

public class CustomJpaPagingItemReader<T> extends AbstractPagingItemReader<T> {

    private EntityManagerFactory entityManagerFactory;
    private EntityManager entityManager;
    private final Map<String, Object> jpaPropertyMap = new HashMap<String, Object>();
    private String queryString;

    private JpaQueryProvider queryProvider;
    private Map<String, Object> parameterValues;

    private boolean transacted = true;

    private Query createQuery() {
        if (!entityManager.isOpen()) {
            System.out.println("CustomJpaPagingItemReader.createQuery()");

            entityManager = entityManagerFactory.createEntityManager(jpaPropertyMap);
            if (entityManager == null) {
                throw new DataAccessResourceFailureException("Unable to obtain an EntityManager");
            }
            // set entityManager to queryProvider, so it participates
            // in JpaPagingItemReader's managed transaction
            if (queryProvider != null) {
                queryProvider.setEntityManager(entityManager);
            }
        }
        if (queryProvider == null) {
            return entityManager.createQuery(queryString);
        }
        else {
            return queryProvider.createQuery();
        }
    }

    public void setEntityManagerFactory(EntityManagerFactory entityManagerFactory) {
        this.entityManagerFactory = entityManagerFactory;
    }

    public void setParameterValues(Map<String, Object> parameterValues) {
        this.parameterValues = parameterValues;
    }

    @Override
    public void afterPropertiesSet() throws Exception {
        super.afterPropertiesSet();

        if (queryProvider == null) {
            Assert.notNull(entityManagerFactory);
            Assert.hasLength(queryString);
        }
        // making sure that the appropriate (JPA) query provider is set
        else {
            Assert.isTrue(queryProvider != null, "JPA query provider must be set");
        }
    }

    @Override
    protected void doOpen() throws Exception {
        if (entityManager == null) {
            super.doOpen();
            entityManager = entityManagerFactory.createEntityManager(jpaPropertyMap);
            if (entityManager == null) {
                throw new DataAccessResourceFailureException("Unable to obtain an EntityManager");
            }
            // set entityManager to queryProvider, so it participates
            // in JpaPagingItemReader's managed transaction
            if (queryProvider != null) {
                queryProvider.setEntityManager(entityManager);
            }
        }

    }

    public void setQueryString(String queryString) {
        this.queryString = queryString;
    }

    public void setQueryProvider(JpaQueryProvider queryProvider) {
        this.queryProvider = queryProvider;
    }

    public void setTransacted(boolean transacted) {
        this.transacted = transacted;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void doReadPage() {

        /*EntityTransaction tx = null;
        
        if (transacted) {
            tx = entityManager.getTransaction();
            //tx.begin();
            entityManager.flush();
            entityManager.clear();
        }*/

        Query query = createQuery().setFirstResult(getPage() * getPageSize())
                .setMaxResults(getPageSize());

        if (parameterValues != null) {
            for (Map.Entry<String, Object> me : parameterValues.entrySet()) {
                query.setParameter(me.getKey(), me.getValue());
            }
        }

        if (results == null) {
            results = new CopyOnWriteArrayList<T>();
        }
        else {
            results.clear();
        }

        /*if (!transacted) {
            List<T> queryResult = query.getResultList();
            for (T entity : queryResult) {
                entityManager.detach(entity);
                results.add(entity);
            } //end if
        }
        else {
            results.addAll(query.getResultList());
            tx.commit();
        }*/
        results.addAll(query.getResultList());

    }

    @Override
    protected void doJumpToPage(int itemIndex) {
        // TODO Auto-generated method stub

    }

    @Override
    protected void doClose() throws Exception {
        //entityManager.close();
        super.doClose();
        //entityManager.close();
    }

}
](url)

I just commented entitymangement close and kept some conditions in doOpen and  createQuery methods.  After comment it start working fine with out having any issue. please have a look. I think i am not closing entitymanagement and i know this is not good practice. but this is just work around. but good thing is our JPA will automatically close after some period. 

I am waiting for your suggestions to do properly. Thanks again for your help.

**Comment by benas** [comment]
Hi,

You don't need to create a custom reader and ignore the `entityManager.close` method.

Here are a couple of things you might fix in addition to the previous ones:

* remove `@EnableTransactionManagement` on `BatchScheduler` since it is already defined on `BatchConfiguration`
* In your reader, don't get the entity manager from the transaction manager, take the one injected in your class:

```diff
+ fullfillment.setEntityManagerFactory(entityManagerFactory);
- //fullfillment.setEntityManagerFactory(tm.getEntityManagerFactory());
```

* Same in your writer, you could define as follows:

```
@Bean
    public ItemWriter<QuoteOfferFulfillment> writer() {
        return new Writer(fulfillmentRepository, entityManagerFactory,
                offersEngineJobProperties,
                requestProcessor());
    }
```

* You set the page size to 40 in your reader, but the chunk size to 1 in your step. It would be better for performance to set these two parameters to the same value (See [here](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/database/JpaPagingItemReader.java#L55))

Hope this helps.
